rxRust/rxRust

- CHANGELOG.md
- src/lib.rs
- src/observable/interval.rs
- src/ops.rs
- src/ops/delay.rs
- src/ops/filter.rs
- src/ops/first.rs
- src/ops/map.rs
- src/ops/observe_on.rs
- src/ops/subscribe_on.rs
- src/ops/take.rs
- src/ops/throttle_time.rs
- src/scheduler.rs
- src/scheduler/thread_pool_scheduler.rs
- src/scheduler/thread_scheduler.rs
- src/subscriber.rs
- src/subscription.rs
> Throttle time

- README.md
trivially bumping up latest suggested version to 0.4.0
> Updating latest version in README.

- CHANGELOG.md
- src/ops.rs
- src/ops/last.rs
This a `last` and `last_or` operator implementation and unit tests.
> Implementation of last and last_or operators.

- README.md
- missing_features.md
Add a **Missing Features List** so that people can contribute easily. Fix #42
> docs: add a missing features list

- .gitignore
- src/subject.rs
- src/subscribable.rs
- src/subscription.rs
> Add a `Subject::local_new` method let user give an explicit type for `Publisher`. Fix #47

- missing_features.md
- src/ops.rs
- src/ops/take_last.rs
This pr add TakeLast operator.
> feat: add TakeLast operator

- .github/workflows/grcov.yml
Suppresses the annoying X mark and failure notification due to https://github.com/codecov/codecov-action/issues/29.
> Disable coverage for PRs

- src/subscription.rs
> Removed unneeded transmute

- CHANGELOG.md
- src/observable/connectable_observable.rs
- src/observable/from_future.rs
- src/observable/interval.rs
- src/observable/observable_all.rs
- src/observable/observable_comp.rs
- src/observable/observable_err.rs
- src/observable/observable_next.rs
- src/ops/delay.rs
- src/ops/merge.rs
- src/ops/observe_on.rs
- src/ops/publish.rs
- src/ops/subscribe_on.rs
- src/ops/throttle_time.rs
- src/subject.rs
- src/subscription.rs
provide method `unsubscribe_when_dropped()` on subscription
which activates RAII for that subscription
> Make RAII behavior optional

- CHANGELOG.md
- src/ops.rs
- src/ops/box_it.rs
- src/ops/delay.rs
- src/ops/merge.rs
- src/ops/observe_on.rs
- src/ops/subscribe_on.rs
- src/shared.rs
@helgoboss  I provide a way to box observable across an operator named `box_it`. You can review it if you have time.
> feat: add a box_it operator to box observable

- CHANGELOG.md
- src/observable.rs
- src/ops.rs
- src/ops/take_until.rs
@M-Adoo Is it okay to just provide a single-threaded version of the operator for now?
> Add take_until operator

- .github/workflows/grcov.yml
after [codecov-action](https://github.com/codecov/codecov-action/issues/29) fixed, we can enable
coverage for PRs now
> ci: enable coverage for pr

- .gitignore
- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/default_if_empty.rs
Now we can use `deault_if_empty(x)`
It will emit `x` when observable compete with empty results.
> Feat add default if empty operator

- CHANGELOG.md
- src/observable.rs
- src/ops.rs
- src/ops/sample.rs
Change-Id: I7c15bae158461681ea3b37439eeaf3167f31001e
> feat: add sample operator

- CHANGELOG.md
- src/lib.rs
- src/observable.rs
- src/observable/connectable_observable.rs
- src/observer.rs
- src/ops/map_to.rs
- src/ops/ref_count.rs
- src/subject.rs
- src/subject/mut_ref_subject.rs
> Remove PayloadCopy and require Clone instead

- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/debounce.rs
- src/ops/distinct.rs
- src/ops/throttle_time.rs
Implement debounce, distinct operator
> Implement debounce, distinct operator

- src/ops/skip_last.rs
Where to write the test? Please help.
> Implement element_at, ignore_elements, refactor distinct

- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/skip_while.rs
It's mostly a copy-paste from `take_while` module. I just started learning Rust and plan to rely on Rx, so I thought it'd be a good idea to get familiar with the language by contributing to the project with easier tasks.
> Implement skip_while operator

- src/observable.rs
- Use trait inheritance instead of a lot of `where Self: Sized`
> Refactor Observable

- CHANGELOG.md
- missing_features.md
- src/observable.rs
> Implement `all` operator

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/contains.rs
> Implement `contains` operator

- src/ops/filter.rs
Will adding bench mark testing helpful for **missing_features.md/Workflows/ci/benchmark**?
> Add bench for filter

- src/observable/connectable_observable.rs
- src/observable/from_fn.rs
- src/observable/from_future.rs
- src/observable/from_iter.rs
- src/observable/of.rs
- src/ops/box_it.rs
- src/ops/contains.rs
- src/ops/default_if_empty.rs
- src/ops/distinct.rs
- src/ops/filter_map.rs
- src/ops/finalize.rs
- src/ops/last.rs
- src/ops/map.rs
- src/ops/map_to.rs
- src/ops/merge.rs
- src/ops/observe_on.rs
- src/ops/ref_count.rs
- src/ops/scan.rs
- src/ops/skip.rs
- src/ops/skip_last.rs
- src/ops/skip_while.rs
- src/ops/take.rs
- src/ops/take_last.rs
- src/ops/take_until.rs
- src/ops/take_while.rs
- src/ops/zip.rs
- add bench base on other tests
- move some test to test crate
> Add bench tests

- .mergify.yml
> Update mergify messages

- src/observable.rs
- src/ops.rs
This operator allows composing Observables with functions that return Observables on its own. It was implemented using a combination of the `map` and `flatten` operators
> feat: 🎸 add flat_map operator

- Cargo.toml
- src/scheduler.rs
Addresses issue #146.
Tests are passing but I have not tested the crate thoroughly. There were no actual runtime code changes, just the name of the features and test code.
> Update to tokio 1

- src/observable.rs
solves https://github.com/rxRust/rxRust/issues/148
> Publish <of> module for use in function return types to solve for #148

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/group_by.rs
Implementation of the GroupBy operator. It groups items into Observables by the keys, obtained from the discriminator function.
> feat: Implement group_by operator.

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/combine_latest.rs
Implemented combine_latest operator. It emits item which is combining latest items from two observables.
> feat: 🎸 Implement combine_latest operator

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/with_latest_from.rs
This revisions includes:
- Add operator 'WithLatestFrom' (See https://rxmarbles.com/#withLatestFrom)
- Create struct 'WithLatestFromOp'
- Add function 'with_latest_from()'
p.s. I tried to inspire my implementation on operator 'Zip'.
> Add operator 'WithLatestFrom'

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/observable/start.rs
Implementation for the [start](http://reactivex.io/documentation/operators/start.html) operator
> feat: Add operator 'start'

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops/distinct.rs
Implemented distinct_until_changed operator. It only emits when the current value is different than the last.
> feat: 🎸 Implement distinct_until_changed operator

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/tap.rs
Add [`do` operator](https://reactivex.io/documentation/operators/do.html), 
but named it as `tap` to avoid ambiguity with reserved keyword `do`.
> feat: 🎸 Implement `tap` operator

- src/ops/start_with.rs
`start_with` operator starts emitting items when the first item is emitted from the source.
But, from my understanding, this is not correct behavior, regarding the document of RxJS: https://rxjs.dev/api/operators/startWith
> Returns an observable that, at the moment of subscription, will synchronously emit all values provided to this operator, then subscribe to the source and mirror all of its emissions to subscribers.
So, I fixed the behavior of `start_with` operator to do so.
> Let `start_with` starts on subscription

- CHANGELOG.md
- missing_features.md
- src/observable.rs
- src/ops.rs
- src/ops/box_it.rs
- src/ops/filter_map.rs
- src/ops/group_by.rs
- src/ops/throttle.rs
- src/ops/throttle_time.rs
- src/test_scheduler.rs
This revisions includes:
- Add operator 'Throttle' (See https://rxmarbles.com/#throttle)
- Create struct 'ThrottleOp'
- Add function 'throttle()'
- Rename 'Throttle' to 'ThrottleTime'
p.s. I tried to inspire my implementation on operator 'ThrottleTime'.
> Add operator 'Throttle'

- src/observable.rs
> Update old group_by example in the docs

- CHANGELOG.md
- src/observable.rs
- src/ops/group_by.rs
This PR attempts to fix the issue mentioned in #201, but unfortunatly there is a type error still in there I have not been able to fix so far.
> Only subscribe to source once

- src/ops/group_by.rs
Due to an oversight during implementation, `error` and `complete` signals did not get forwarded to the `observables` emitted by the `group_by` operation.
This commit fixes this, iterating through all stored `subjects` of the operator on completion/error.
> Propagate error & complete to group_by groups

- CHANGELOG.md
- Cargo.toml
- src/observable.rs
- src/observable/from_stream.rs
- src/observable/from_stream_result.rs
Added factories `observable::from_stream` and `observable::from_stream_result`
> Added from_stream and from_stream_result factory functions
