.github/main.workflow
README.md
src/lib.rs
src/ops/filter.rs
src/ops/map.rs
src/ops/merge.rs
src/subject.rs

Now use `rx_rs` in this way:
```rust
subject
.map(...)
.filter(...)
.subscribe(|v| { ... })
// if need error handding
.on_error(|err| { ... })
// completed process, if need
.on_complete(|| { ... });
```

refactor: split `on_error` and `on_complete` from `subscribe` method

---

CHANGELOG.md
README.md
src/observable.rs
src/observable/connectable_observable.rs
src/observable/from.rs
src/observable/from_future.rs
src/ops/delay.rs
src/ops/filter.rs
src/ops/first.rs
src/ops/fork.rs
src/ops/map.rs
src/ops/merge.rs
src/ops/observe_on.rs
src/ops/publish.rs
src/ops/ref_count.rs
src/ops/subscribe_on.rs
src/ops/take.rs
src/ops/throttle_time.rs
src/scheduler.rs

I'm proposing a change that (partially) addresses #23 and replaces macros with plain strongly typed and constrained functions.
Hope you'll find it useful for further development.

Macros of!, empty! and from_iter! replaced by functions.

---

CHANGELOG.md
src/ops.rs
src/ops/scan.rs

Here is a simple implementation and tests for the `scan` operator.
I find implementation of it very helpful to extend the overall operator set of the library, as plenty of [Mathematical and Aggregate Operators](http://reactivex.io/documentation/operators.html#categorized) could be implemented indirectly with `scan` and `last` operators chained. 
With Rust code optimisation, they should have a comparable performance as hand-crafted individually.

Adding scan operator.

---

.github/workflows/lint_and_test.yml
src/observable/interval.rs
src/ops/throttle_time.rs
src/subject.rs

before we have a virtual timer, we can use a longer duration to let the unit test more reliable

use a longer duration to let the unit test more reliable

---

CHANGELOG.md
src/observable.rs
src/observable/from.rs
src/observable/trivial.rs
src/subscribable.rs
src/subscribable/subscribable_all.rs
src/subscribable/subscribable_comp.rs
src/subscribable/subscribable_err.rs
src/subscribable/subscribable_pure.rs
src/subscriber.rs

This MR is about to extend `rxrust` with a set of trivial observables:
never()
from_fn(...) -> AKA start
throw(...)
repeat(...)
as defined on [ReactiveX.io ](http://reactivex.io/documentation/operators.html#categorized) operators.
Also, a trivial observable constructors from Rust-specific `Result<T,E>` and `Option<T>` types:
of_result(...)
of_option(...)
I plan to implement them as functions, therefore the starting point for this MR is the `removing-from-macros` branch (so the diff to master as visible here is not 100% adequate for the time being).

New trivial observables

---

src/ops/scan.rs

Fixing the issue with scan operator.
- unit test reproducer added,
- `InputItem` / `OutputItem` type conventions in code of `scan` re-done, to form a clearer pass down the code, leading to correctly composing operators now.
Side change as well: correcting the name of `binary_op` argument in `scan` docstring,

Scan operator fix for #36

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
src/lib.rs
src/ops.rs
src/ops/average.rs
src/ops/count.rs
src/ops/map.rs
src/ops/minmax.rs
src/ops/reduce.rs
src/ops/scan.rs
src/ops/sum.rs

This PR aims to provide a collection of Mathematical and Aggregate Operators operators:
They are mainly implemented indirectly as a composition of already existing ones like scan/last/map etc for few reasons:
- Rust should nicely optimise out all the boilerplate and result with still lean and performant code after compilation,
- we reduce a boilerplate code of plumbing things together in a similar way,
- it's a nice challenge to existing operators and how they compose, so potentially will reveal their weak points early.
Work in progress...

Adding a set of math and aggregate operators

---

rustfmt.toml
src/lib.rs
src/observable/connectable_observable.rs
src/observer.rs
src/ops/filter.rs
src/ops/filter_map.rs
src/ops/first.rs
src/ops/last.rs
src/ops/map.rs
src/ops/merge.rs
src/ops/observe_on.rs
src/ops/publish.rs
src/ops/ref_count.rs
src/ops/scan.rs
src/ops/take.rs
src/ops/throttle_time.rs
src/subject.rs
src/subscribable.rs
src/subscribable/subscribable_all.rs
src/subscribable/subscribable_comp.rs
src/subscribable/subscribable_err.rs
src/subscribable/subscribable_pure.rs
src/subscriber.rs

This pr resolve two problem of subject emit mut ref item.
1.  When use subject emit mut ref item or mut ref error, infer type not work, we must write like this
```rust
// emit mut ref
type MutRefObserver<Item> = Box<dyn for<'r> Publisher<&'r mut Item, ()>>;
let mut subject: Subject<LocalObserver<MutRefObserver<i32>>, _> =
Subject::local_new();
subject
.fork()
.subscribe((|_: &mut _| {}) as for<'r> fn(&'r mut i32));
subject.next(&mut 1);
```
A more elegant way should like this:
``` rust
// emit mut ref
let mut subject = Subject::local_mut_ref_item();
subject.fork().subscribe(|_: &mut _| {});
subject.next(&mut 1);
```
2. We introduced a trait `SubjectCopy` in 0.7.1,  but only primitive and `&mut T` auto  implemented it, and a type must implemented `SubjectCopy` can be emit by `Subject`, …

Mut ref elegant

---

CHANGELOG.md
src/observable/connectable_observable.rs
src/observer.rs
src/ops/filter_map.rs
src/ops/publish.rs
src/ops/ref_count.rs
src/subject.rs

This commit merge four version local subject into same one. Now we can emit value by mut ref like this:
```rust 
let mut i = 1;
let mut subject = Subject::local();
subject.fork().subscribe(|v: &mut _| { *v = 100; });
subject.next(&mut i);
assert_eq!(i, 100);
```

refactor: merge 4 version local subject into one

---

src/lib.rs
src/observable/interval.rs
src/ops/throttle_time.rs

This pr replace macros `interval!` and `interval_at!` with functions as I suggested in #23. 
BTW, I notice this project uses generics a lot, but too many generics may slow down compilation when this project grows large. For example, `diesel` use generics a lot and it compiles really slow.  I think compilation time does matter.

refactor: replace macros interval and interval_at with functions

---

Cargo.toml
src/subscription.rs

Replaces the `Teardown` type (probably coded to save space?) with a more generic implementation from the `smallvec` crate.
This makes the implementation less error prone.

Replace in-house implementation with smallvec

---

CHANGELOG.md
src/lib.rs
src/observable.rs
src/observable/from.rs
src/observable/from_future.rs
src/observable/interval.rs
src/observable/trivial.rs
src/ops/first.rs
src/ops/last.rs
src/ops/merge.rs
src/ops/observe_on.rs
src/subscribable/subscribable_all.rs
src/subscribable/subscribable_comp.rs
src/subscribable/subscribable_err.rs
src/subscribable/subscribable_pure.rs
src/subscription.rs

1. Rename Observable to ObservableFromFn
2. Remove `Observable::new`, and add a same `new` function in `observable` mod to replace it

Refactor concrete observable

---

CHANGELOG.md
src/observable/observable_all.rs
src/observable/observable_comp.rs
src/observable/observable_err.rs
src/observable/observable_next.rs
src/subscription.rs

Hi,
I added the [must_use](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute) attribute to the SubscriptionGuard.
This makes sure you don't forget to assign it to sth. after a call to `unsubscribe_when_dropped`.
Example compiler warning if you forget:
```
warning: unused subscription::SubscriptionGuard that must be used
--> src/observable/observable_all.rs:117:7
|
117 | /       subject
118 | |         .clone()
119 | |         .subscribe_all(|_| times += 1, |_| {}, || {})
120 | |         .unsubscribe_when_dropped();
| |____________________________________^
|
= note: #[warn(unused_must_use)] on by default
Finished test [unoptimized + debuginfo] target(s) in 7.73s
Running `target/debug/deps/rxrust-78871ff7dfcfd963`
```
The warning disappears once you use …

feat: SubscriptionGuard has the #must_use attribute

---

CHANGELOG.md
src/lib.rs
src/observable.rs
src/observable/connectable_observable.rs
src/observer.rs
src/ops/ref_count.rs
src/subject.rs
src/subject/mut_ref_subject.rs

This solves #74. 
Implementing `PayloadCopy` for built-in non-copyable types like `Rc` or `Cell` seems to be impossible (I think because `Copy` is not a fundamental type). That's not a big deal though because users can always create their own lightweight wrapper types (e.g. using newtype pattern).

Relax Copy bound, introduce PayloadCopy instead

---

CHANGELOG.md
src/observable.rs
src/observable/of.rs

Hey! With of_sequence will possibly create observable from custom sequences of values like:
```rust
of_sequence!(1, 2, 3)
```

Feat: Add of_sequence macros

---

CHANGELOG.md
src/observable/connectable_observable.rs
src/ops/filter_map.rs
src/subject/mut_ref_subject.rs

Becasuse the lifetime of mut ref will be erased.

fix: mark methods that to create a MutRefSubjet as unsafe

---

src/subject/local_subject.rs

Would be great if most of the public high-level structs in rxRust implemented `Debug`. Here's a start for `LocalSubject`.

Implement Debug for LocalSubject

---

README.md

I think this was intention of original author. Maybe it could be changed to "to know what rxRust is missing"

Fix grammer

---

src/observable.rs
src/ops.rs
src/ops/flatten.rs

This operator allows merging multiple Observables together by creating an Observable of Observables. This operator makes the implementation of flat_map somewhat trivial, as it is the combination of `map` and `flatten.`
The performance of this operator is not as performant if compared to others. This behaviour makes sense as I keep the operator state on the heap. My Rust knowledge is not advanced enough to move the performance of this operator further. There might be a chance for improvement.

Add flatten operator

---

missing_features.md
src/observable.rs
src/observable/defer.rs

An implementation to create an observable by defering to another observable supplied by a function.

Implement defer

---

src/observable.rs
src/observable/interval.rs
src/observable/observable_block.rs
src/observable/observable_block_all.rs
src/ops/delay.rs
src/subject.rs

This PR partially addresses https://github.com/rxRust/rxRust/issues/26 by implementing subscribe blocking on shared observables. Using this `observable::interval::tests::shared` as well as `ops::delay::tests::shared_smoke` tests becomes stable without timing issues.
It's only implemented on shared observables, since local observables blocks by nature making a local observble implementation confusing, if I'm not mistaken.
`ops::throttle_time::tests::smoke`,` ops::sample::test::sample_base`, and  are still unstable as they operate on a local scheduler. As the subscribe_blocking function blocks the executing thread this means that that same thread cannot be used to schedule new intervals causing an infinite lock. Therefore, testing a local emitter using a local scheduler becomes impossible …

Implement subscribe blocking for shared observables

---

src/lib.rs
src/observable/from_future.rs
src/observable/interval.rs
src/ops/sample.rs
src/ops/throttle_time.rs
src/scheduler.rs
src/test_scheduler.rs

A first implementation of a test scheduler with its own timekeeping.
This fixes https://github.com/rxRust/rxRust/issues/26
This implementation required public API change:
_IntervalEmitter takes at as an option, the implicit Instant::now() call messes with virtual timekeeping if a clock isn't passed as an arg, which is cumbersome_
Functional changes:
_Interval generation gets outsourced to the scheduler_
This implementation could be applied to the shared scheduler as well if you want, but I left it to the local for the moment.
Would love feedback on this larger commit!

Implement manual test scheduler

---

CHANGELOG.md
missing_features.md
src/observable.rs
src/observable/timer.rs

Adds the timer operator.
Usage is either by a given ```Duration```
```rust
observable::timer(val, Duration::from_millis(5), scheduler)
```
or by a given ```Instant```
```rust
observable::timer_at(val, Instant::now() + Duration::from_millis(5), scheduler)
```
Emitter is implemented for both local and shared schedulers.
As this is my first PR in this repo, i tried to inspire my implementation on ```observable::interval```.

Add timer operator

---

CHANGELOG.md
missing_features.md
src/behavior_subject.rs
src/lib.rs
src/observable/trivial.rs
src/subject/local_subject.rs
src/subject/shared_subject.rs

This revisions includes:
- Add struct 'BehaviorSubject' (See http://reactivex.io/documentation/subject.html)
- Implement local subject for 'BehaviorSubject'
- Implement shared subject for 'BehaviorSubject'
p.s. As this is my first PR in this repo, i tried to inspire my implementation on struct 'Subject'.

Add subject 'BehaviorSubject'

---

missing_features.md

Some of the already implemented operators are missing in missing_features.md:
- flat_map
- sample
- subscribe
- skip_while
- take_until

docs: Check already implemented operators in missing_features

---

README.md

- Correct minor typos in README.md
- Fix Markdown style
- Fix version to '1.0.0-alpha.2'

Correct minor typos in README.md

---

CHANGELOG.md
missing_features.md
src/observable.rs
src/ops.rs
src/ops/start_with.rs

This revisions includes:
- Add operator 'StartWith' (See http://reactivex.io/documentation/operators/startwith.html)
- Create struct 'StartWithOp'
- Add function 'start_with()'

Add operator 'StartWith'

---

src/observable.rs
src/ops/take_while.rs

Implemented take_while_inclusive operator.
This is take_while operator with inclusive flag on in RxJS. I made this as separate operator to avoid breaking existing interface of take_while. But I think it's less ugly when we make it as a parameter of existing `take_while` operator, like `take_while(predicate, false)` or `take_while(predicate, true)`.

feat: 🎸 Implement take_while_inclusive operator

---

CHANGELOG.md
src/observable.rs
src/ops/distinct.rs

Implement `distinct_key` and `distinct_key_until_changed` operator.
Each operators are variant of `distinct` and `distinct_until_changed` respectively. They work the same way except that comparison is done on the result of given key selector.

feat: 🎸 Implement `distinct_key` and `distinct_key_until_changed` operator

---

CHANGELOG.md
src/ops/with_latest_from.rs

If you run newly added test `ops::with_latest_from::test::circular`, will get following error.
<details>
<summary>error message</summary>
already borrowed: BorrowMutError
thread 'ops::with_latest_from::test::circular' panicked at 'already borrowed: BorrowMutError', src/rc.rs:103:62
stack backtrace:
0: rust_begin_unwind
at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:498:5
1: core::panicking::panic_fmt
at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:107:14
2: core::result::unwrap_failed
at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/result.rs:1613:5
3: core::result::Result<T,E>::expect
at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/result.rs:1255:23
4: …

Make `with_latest_from` operator able to recurse

---

CHANGELOG.md
src/observable.rs
src/ops.rs
src/ops/pairwise.rs

Implemented `pairwise` operator. It groups pairs of consecutive emissions together and emits them as an pair of two values.

feat: 🎸 Implement `pairwise` operator

---

src/observable.rs
src/ops/start_with.rs

- Replace trait 'Fn' with 'FnMut'
- My project should call method using `&mut self` in operator `map`. To resolve this problem, the trait `Fn` should replace with `FnMut`.

Replace trait 'Fn' with 'FnMut'

---

src/ops/take_until.rs
src/subject.rs

If you run newly added test `ops::take_until::test::circular`, will get following error.
<details>
<summary>error message</summary>
```
already borrowed: BorrowMutError
thread 'ops::take_until::test::circular' panicked at 'already borrowed: BorrowMutError', src/rc.rs:103:62
stack backtrace:
0: rust_begin_unwind
at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/std/src/panicking.rs:498:5
1: core::panicking::panic_fmt
at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/core/src/panicking.rs:107:14
2: core::result::unwrap_failed
at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/core/src/result.rs:1660:5
3: core::result::Result<T,E>::expect
at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/core/src/result.rs:1302:23
4: core::cell::RefCell<T>::borrow_mut
at …
```

Subscription in two steps to avoid `already borrow`

---

src/observable.rs
src/ops/default_if_empty.rs
src/ops/group_by.rs
src/ops/observe_on.rs
src/subscription.rs

- Correct minor typos
- Rename variables for improving readability

Correct minor typos and rename variables

---

README.md

- Correct information
- Update crate 'rxrust' to '1.0.0-alpha.3'
- Correct output of the example

Correct information

---

Cargo.toml
src/lib.rs
src/observable/interval.rs
src/scheduler.rs
src/test_scheduler.rs

With current implementation of `wasm-scheduler` you will get error like following when you use interval operator.
As far as I understand, this is because
1. `interval` operator uses `scheduler_repeating` function of `LocalScheduler` trait.
2. Default implementation of `scheduler_repeating` uses `std::time::Instant::now()`. Once in the function body, another  in the implementation of `async_std::stream::interval`.
3. We cannot use `std::time::Instant::now()` in the WASM(I am just assuming this following [this README](https://github.com/sebcrozet/instant#instant). Let me know if I am wrong)
My suggestion here is that using `fluvio-wasm-timer` library. 
When we use this library in other platforms, it will re-export `std::time::Instant`.
If we use it for WASM, it will provide us …

fix: make `wasm-scheduler` runnable on the browser

---

src/lib.rs
src/observable/interval.rs
src/scheduler.rs
src/test_scheduler.rs

In the previous PR(#189), I included Instant type in the prelude. 
But now I think this is bad idea, because if the use of rxRust does following,
```rust
use rxrust::prelude::*;
use std::time::Instant;
```
it will cause name collision. And I think this can happen quite often.

fix: don't re-export Instant

---

src/lib.rs
src/observable.rs
src/observable/observable_block.rs
src/observable/observable_block_all.rs
src/observable/timer.rs
src/ops/debounce.rs
src/ops/delay.rs
src/scheduler.rs
src/subject.rs
src/subject/behavior_subject.rs

Problem in #190 is that it requires me to add fluvio-wasm-timer separately in the cargo.
Say, if you make timer observable, you will provide value of `Instant` as a argument, 
so you need to add the dependency of fluvio-wasm-timer to make target-indenpendant `Instant`.
I think I misunderstood what @M-Adoo in the previous PR, so here is a little modification.
We will export `fluvio_wasm_timer::Instant` through `rxrust::scheduler::Instant`, but not as `rxrust::prelude::Instant`.
Additionally I updated internal use of `Instant`s from `std::time::Instant` to `crate::scheduler::Instant`.

fix: revise the interface of Instant

---

src/ops/merge_all.rs

- Ignore clippy issue temporarily
- Calling `&mut Mutex::lock` unnecessarily locks an exclusive (mutable) reference
- Reference: https://rust-lang.github.io/rust-clippy/master/index.html#mut_mutex_lock
- I think that it's false positive
- Reference: https://github.com/rust-lang/rust-clippy/issues/9415

Ignore clippy issue

---

Cargo.toml
src/lib.rs
src/ops/tap.rs
src/scheduler.rs

- Fix problem that operator 'interval()' is delayed in WebAssembly
- Add crate 'gloo-timers'
- Replace code 'fluvio_wasm_timer::Interval' with 'IntervalStream'

Fix problem that operator 'interval()' is delayed in WebAssembly

---

src/ops/group_by.rs

The `Source` for `impl<Source, Discr, Key> SharedObservable  for GroupByOp` does not need to implement `Clone`

Fix unnecessary `Clone` requirement for shared_obs

---

src/observable.rs
src/ops.rs
src/ops/on_error_map.rs

This method can be used to map errors from `A` to `B`

Add `on_error_map` operation

---

CHANGELOG.md
README.md
src/observable.rs
src/ops/delay.rs
src/ops/observe_on.rs
src/ops/subscribe_on.rs
src/ops/throttle.rs
src/scheduler.rs

1. fix `delay` operator not really delay the emission but delay subscribe; 
2. add `delay_subscription` to only delay the initial subscription
3. fix unsubscribe the handle of parallels scheduler not always cancel the remote task correctly

Fix `delay` op  not really delay emission and  related bugs.

---

CHANGELOG.md
src/observable.rs
src/observable/fake_timer.rs
src/observable/from_future.rs
src/observable/from_iter.rs
src/observable/from_stream.rs
src/observable/interval.rs
src/observable/of.rs
src/observable/subscribe_item.rs
src/observable/timer.rs
src/observable/trivial.rs
src/ops.rs
src/ops/box_it.rs
src/ops/buffer.rs
src/ops/merge.rs
src/ops/on_error.rs
src/ops/on_error_map.rs
src/subject.rs

As commented in #222 `Infallible` should be used instead of `()` for representing errors that can not happen

Changed unit for infallible to represent errors that can never happen.

---

src/observable/from_future.rs

Fixed missing change from `()` to `Infallible` in `from_future`.
See: #222

fix: 🐛 changed error type to infallible for from_future

---

missing_features.md
src/observable.rs
src/ops/buffer.rs

The signature is similar to [RxJS's buffer](https://www.learnrxjs.io/learn-rxjs/operators/transformation/buffer#signature-buffer-closingnotifier-observable-observable)

feat: add ObservableExt::buffer

---

CHANGELOG.md
missing_features.md
src/observable.rs
src/ops.rs
src/ops/merge_all.rs

I found this trick from [RxJS's document](https://rxjs.dev/api/operators/concatAll#:~:text=Note%3A%20concatAll%20is%20equivalent%20to%20mergeAll%20with%20concurrency%20parameter%20set%20to%201.):
> Note: [concatAll](https://rxjs.dev/api/index/function/concatAll) is equivalent to [mergeAll](https://rxjs.dev/api/index/function/mergeAll) with concurrency parameter set to 1.
The test case for `concat_all` successfully reproduced RxJS's behavior https://stackblitz.com/edit/zs9ohl?devtoolsheight=50&file=index.ts

feat: add concat_map and concat_all

---

src/ops/future.rs

Not having `Clone` prevents `ObservableError` from being sent between multi-threading observables. It would be nice to provide a `Clone` implementation for `ObservableError`

Derive Clone for ObservableError

---

src/scheduler.rs

I suppose it was a remnant from testing that you would print out the unsubscribe event. When using the library it is unfortunate that you get stdout/stderr text to the command line, so I'm removing it from here.

Remove `eprintln` on unsubscribe

---

CHANGELOG.md
src/rc.rs
src/subject.rs
src/subject/behavior_subject.rs

This pull request includes a new trait called `AssociatedRefPtr` in order to fix #248
There are many operators in rxRust with similar functionality, but differentiated on the basis that some are thread safe are others aren't. There has been work done to merge some of them (for example, `LocalBehaviorSubject` and `SharedBehaviorSubject` got merged into `BehaviorSubject`), letting the thread safety be managed by generics. This creates the need for the wrapping operator (e.g. `BehaviorSubject` in this case) to know which reference counting pointer implementation to use in its internal implemetation, the atomic one (`Arc<Mutex<>>` aka. `ArcMut`) or the simple one that's not thread safe (`Rc<RefCell<>>` or `RcMut`), based just on the operator in its generics.
The `AssociatedRefPtr` contains …

RFC: Associate Reference Counting Pointers with Operators based on thread safety
